2022-09-29 05:47:08,530 INFO    MainThread:464 [wandb_setup.py:_flush():68] Configure stats pid to 464
2022-09-29 05:47:08,531 INFO    MainThread:464 [wandb_setup.py:_flush():68] Loading settings from C:\Users\bhatt\.config\wandb\settings
2022-09-29 05:47:08,531 INFO    MainThread:464 [wandb_setup.py:_flush():68] Loading settings from C:\Users\bhatt\OneDrive\Documents\MLOps\week_1_wandb_logging\experimental_notebooks\wandb\settings
2022-09-29 05:47:08,531 INFO    MainThread:464 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-09-29 05:47:08,531 INFO    MainThread:464 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-09-29 05:47:08,531 INFO    MainThread:464 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2022-09-29 05:47:08,532 INFO    MainThread:464 [wandb_init.py:_log_setup():476] Logging user logs to C:\Users\bhatt\OneDrive\Documents\MLOps\week_1_wandb_logging\experimental_notebooks\wandb\run-20220929_054708-2loscota\logs\debug.log
2022-09-29 05:47:08,532 INFO    MainThread:464 [wandb_init.py:_log_setup():477] Logging internal logs to C:\Users\bhatt\OneDrive\Documents\MLOps\week_1_wandb_logging\experimental_notebooks\wandb\run-20220929_054708-2loscota\logs\debug-internal.log
2022-09-29 05:47:08,532 INFO    MainThread:464 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001ADABB6BF40>
2022-09-29 05:47:08,533 INFO    MainThread:464 [wandb_init.py:init():516] calling init triggers
2022-09-29 05:47:08,533 INFO    MainThread:464 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-09-29 05:47:08,533 INFO    MainThread:464 [wandb_init.py:init():569] starting backend
2022-09-29 05:47:08,533 INFO    MainThread:464 [wandb_init.py:init():573] setting up manager
2022-09-29 05:47:08,544 INFO    MainThread:464 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-09-29 05:47:08,554 INFO    MainThread:464 [wandb_init.py:init():580] backend started and connected
2022-09-29 05:47:08,580 INFO    MainThread:464 [wandb_run.py:_label_probe_notebook():1098] probe notebook
2022-09-29 05:47:08,582 INFO    MainThread:464 [wandb_run.py:_label_probe_notebook():1108] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-09-29 05:47:08,582 INFO    MainThread:464 [wandb_init.py:init():658] updated telemetry
2022-09-29 05:47:08,582 INFO    MainThread:464 [wandb_init.py:init():692] communicating run to backend with 30 second timeout
2022-09-29 05:47:12,681 WARNING MsgRouterThr:464 [router.py:message_loop():77] message_loop has been closed
2022-09-29 05:47:38,628 ERROR   MainThread:464 [wandb_init.py:init():703] backend process timed out
2022-09-29 05:47:38,628 ERROR   MainThread:464 [wandb_init.py:init():712] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-09-29 05:55:52,733 INFO    MainThread:464 [wandb_setup.py:_flush():68] Configure stats pid to 464
2022-09-29 05:55:52,733 INFO    MainThread:464 [wandb_setup.py:_flush():68] Loading settings from C:\Users\bhatt\.config\wandb\settings
2022-09-29 05:55:52,733 INFO    MainThread:464 [wandb_setup.py:_flush():68] Loading settings from C:\Users\bhatt\OneDrive\Documents\MLOps\week_1_wandb_logging\experimental_notebooks\wandb\settings
2022-09-29 05:55:52,734 INFO    MainThread:464 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-09-29 05:55:52,734 INFO    MainThread:464 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-09-29 05:55:52,735 INFO    MainThread:464 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2022-09-29 05:55:52,736 INFO    MainThread:464 [wandb_init.py:_log_setup():476] Logging user logs to C:\Users\bhatt\OneDrive\Documents\MLOps\week_1_wandb_logging\experimental_notebooks\wandb\run-20220929_055552-2zr9cntc\logs\debug.log
2022-09-29 05:55:52,736 INFO    MainThread:464 [wandb_init.py:_log_setup():477] Logging internal logs to C:\Users\bhatt\OneDrive\Documents\MLOps\week_1_wandb_logging\experimental_notebooks\wandb\run-20220929_055552-2zr9cntc\logs\debug-internal.log
2022-09-29 05:55:52,736 INFO    MainThread:464 [wandb_init.py:init():516] calling init triggers
2022-09-29 05:55:52,737 INFO    MainThread:464 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-09-29 05:55:52,737 INFO    MainThread:464 [wandb_init.py:init():569] starting backend
2022-09-29 05:55:52,737 INFO    MainThread:464 [wandb_init.py:init():573] setting up manager
2022-09-29 05:55:52,781 ERROR   MainThread:464 [wandb_init.py:init():1103] error
Traceback (most recent call last):
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1076, in init
    run = wi.init()
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\wandb_manager.py", line 170, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\service\service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\bhatt\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
